<div class="hero-unit">
	<h1 style="margin-bottom: 0.2em;"><?php echo "Jump<span class=\"zf-green\">Up</span> Me"?></h1>
	<img style="margin-bottom: 0.2em;" src="img/header.png" />
	<p><?php echo sprintf($this->translate('Hey, Welcome to our all new Platform.')) ?></p>
	<p><?php echo sprintf($this->translate('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.')) ?></p>
	<p style="margin-top:1em;">
		<a class="btn btn-success btn-large" style="margin-right: 3em;"
			href="<?php $this->url(\JumpUpUser\Util\Routes\IRouteStore::REGISTER)?>"
			target="_blank"><?php echo $this->translate(\JumpUpUser\Util\Messages\ILabels::MAINNAV_REGISTER) ?> &raquo;</a>
		<a class="btn btn-success btn-large"
			href="<?php echo $this->url(\JumpUpUser\Util\Routes\IRouteStore::LOGIN)?>"
			target="_blank"><?php echo $this->translate(\JumpUpUser\Util\Messages\ILabels::MAINNAV_LOGIN) ?> &raquo;</a>
	</p>
</div>

<div class="row">

	<div class="span4">
		<h2><?php echo $this->translate('Follow Development') ?></h2>
		<p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
		<p>
			<a class="btn btn-success" href="http://framework.zend.com/zf2"
				target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a>
		</p>
	</div>

	<div class="span4">
		<h2><?php echo $this->translate('Discover Modules') ?></h2>
		<p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
		<p>
			<a class="btn btn-success" href="http://modules.zendframework.com/"
				target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a>
		</p>
	</div>

	<div class="span4">
		<h2><?php echo $this->translate('Help &amp; Support') ?></h2>
		<p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
		<p>
			<a class="btn btn-success"
				href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a>
		</p>
	</div>
</div>
