<h2>Find trips</h2>

<div id="form">
<?php
    if(null != $this->messages) {
        foreach ($this->messages as $message) {
            echo $message . "<br />";
        }    
    }
    
    if(null !== $this->form) {
        // do a rendering process
        $form = $this->form;
        $fields = $this->inputFields;
        $renderingString = $this->renderForm()->startRendering($form)
                              ->appendFields($fields)
                              ->stopRendering($form);
	    echo $renderingString;       
	    // @TODO autocompletion for users inputs start and end location -> binding of gmap coordinates on the hidden input fields
    } 
?>
</div>

<div id="map_div">
      <?php // ..:: the map will be rendered here ::.. ?>
      <div id="map_canvas"></div>     
</div>

<?php 
/*
 * leave the following div empty! It will be filled via jquery.
 */
?>
<div id="accordion">	
</div>


