<h2>Find trips</h2>

<div id="form">
<?php
    if(null != $this->messages) {
        foreach ($this->messages as $message) {
            echo $message . "<br />";
        }    
    }
    
    if(null !== $this->form) {
        // do a rendering process
        $form = $this->form;
        $fields = $this->inputFields;
        $renderingString = $this->renderForm()->startRendering($form)
                              ->appendFields($fields)
                              ->stopRendering($form);
	    echo $renderingString;       
	    // @TODO autocompletion for users inputs start and end location -> binding of gmap coordinates on the hidden input fields
    } 
?>
</div>


