<h2><?php echo $this->translate(\JumpUpPassenger\Util\Messages\IViewMessages::SHOW_TRIPS_TITLE); ?></h2>

<div class="content" id="show-trips">
	<div id="form">
<?php
if (null !== $this->matchedTrips) {
	$matchedTrips = $this->matchedTrips;
	
	foreach ( $matchedTrips as $matchedTrip ) {
		echo $matchedTrip . "<br />";
		// We need to call or inform our map controller in javascript from here....
	}
}

?>
</div>
</div>


