<?php
use Application\Util\Routes\IRouteStore;
echo $this->doctype ();
?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('JumpUp.Me'))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

        <!-- Le styles -->
        <?php
								
								echo $this->headLink ( array (
										'rel' => 'shortcut icon',
										'type' => 'image/vnd.microsoft.icon',
										'href' => $this->basePath () . '/img/favicon.ico' 
								) )->prependStylesheet ( $this->basePath () . '/css/bootstrap-responsive.min.css' )->prependStylesheet ( $this->basePath () . '/css/style.css' )->prependStylesheet ( $this->basePath () . '/css/bootstrap.min.css' )->prependStylesheet ( $this->basePath () . '/css/jMenu.jquery.css' )?>

        <!-- Scripts -->
        <?php
								
								echo $this->headScript ()->setAllowArbitraryAttributes ( true )->prependFile ( $this->basePath () . '/js/html5.js', 'text/javascript', array (
										'conditional' => 'lt IE 9' 
								) )->prependFile ( $this->basePath () . '/js/bootstrap.min.js' )->prependFile ( $this->basePath () . '/js/lib/require-jquery.js', 'text/javascript', array (
										'data-main' => 'js/main' 
								) )?>

    </head>
<body>
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/de_DE/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse"
					data-target=".nav-collapse"> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
				</a> <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('JumpUp.Me') ?></a>
				<div class="nav-collapse collapse flag">
					<ul class="nav">
						<li><a class="flag flag_first"
							href="<?php echo $this->url(IRouteStore::SET_LANG) . '/de' ?>"><img
								src="img/de.png" /> </a></li>
						<li><a class="flag"
							href="<?php echo $this->url(IRouteStore::SET_LANG) . '/en' ?>"><img
								src="img/en.png" /></a></li>
					</ul>
				</div>
				<!--/.nav-collapse -->

				<nav><?php echo $this->navigation('navigation')->menu(); ?></nav>

				<div class="shortprofile">
                    	<?php echo "<a  class=\"userlink\" href=\"".$this->url(\JumpUpUser\Util\Routes\IRouteStore::CHANGE_PROFILE)."\">".$this->renderUser()."</a>"; ?>
                    </div>
			</div>
		</div>
	</div>
	<div id="page-content" class="container">
            <?php echo $this->content; ?>           
        </div>
	<!-- /container -->
	<hr>
	<footer class="row">
		<p class="span11">&copy; <?php echo date('Y') ?> by Martin Schultz &amp; Sascha Feldmann. <?php echo $this->translate('All rights reserved.') ?>
		<div class="fb-like span1" data-href="https://www.facebook.com/Everseek" data-send="false" data-layout="button_count" data-width="150" data-show-faces="true" data-font="segoe ui"></div></p>
	</footer>
        <?php echo $this->inlineScript()?>
    </body>
</html>
