<?php use Application\Util\Routes\IRouteStore;
echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->setAllowArbitraryAttributes(true)
                                      ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') 
                                      ->prependFile($this->basePath() . '/js/lib/require-jquery.js', 'text/javascript', array('data-main' => 'js/main')) ?>

    </head>
    <body>
    	<nav>
    		<?php echo $this->navigation('navigation')->menu(); ?>
    	</nav>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li><a href="<?php echo $this->url(IRouteStore::SET_LANG). '/de' ?>"><?php echo $this->translate('Set german') ?></a></li>
                            <li><a href="<?php echo $this->url(IRouteStore::SET_LANG). '/en' ?>"><?php echo $this->translate('Set english') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>           
        </div> <!-- /container -->
         <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by Martin Schultz &amp; Sascha Feldmann. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
