<h2><?php echo $this->translate(JumpUpUser\Util\Messages\IViewMessages::LOGIN_TITLE); ?></h2>

<?php 
    $form = $this->form;    
 
    //$this->renderForm()->setTranslator($this->translator);
    echo $this->renderForm($form); 
 
     
    if ($this->messages){
        echo '<ul>';
        foreach($this->messages as $message)
        {
            echo '<li>'.$this->translate($message).'</li>';
        }
        echo '</ul>';
    }
?>