<?php
use JumpUpUser\Util\Messages\IViewMessages;
?>
<h2><?php echo $this->translate(IViewMessages::PROFILE_SHOW_TITLE); ?></h2>

<div id="profile_subnav">
	<ul>		
		<?php 
		$linkVehicle = $this->linkVehicle;
		if(null !== $linkVehicle) {
			$linkText = $this->translate(IViewMessages::LIST_VEHICLES);
			echo "<li><a href=\"{$linkVehicle}\">{$linkText}</a></li>\n\t\t\t";
		}
		$linkEdit = $this->linkEdit;
		if(null !== $linkEdit) {
			$linkText = $this->translate(IViewMessages::EDIT_PROFILE);
			echo "<li><a href=\"{$linkEdit}\">{$linkText}</a></li>\n\t\t";
		}
		?>
	</ul>
</div>

<div id="addtrip_hints">
<?php 
if(null !== $this->messages) {
	foreach ($this->messages as $message) {
		echo "<p>".$this->translate($message)."</p>";
	}
}
?>
</div>

<div class="profile">
<?php    
    if(null !== $this->user) {          
         echo $this->renderUser($this->user, false); 
    }
      
?>

</div>

