<h2>Add trip</h2>

<div id="addtrip_hints">
<?php 
if(null !== $this->messages) {
	foreach ($this->messages as $message) {
		echo "<p>".$message."</p>";
	}
}

?>
</div>

<div id="form">
<?php
    if(null !== $this->form) {
        // do a rendering process
        $form = $this->form;
        $fields = $this->fields;
        $renderingString = $this->renderForm()->startRendering($form)
                              ->appendFields($fields)
                              ->stopRendering($form);
	    echo $renderingString;
    }
    else {
        echo $this->translate($this->message);
    }
?>
</div>

<div id="recommended_price">
</div>

    <div id="map_div">
      <?php // ..:: the map will be rendered here ::.. ?>
      <div id="map_canvas"></div>
      <div id="textbox">
       Drag directions and click the map to geocode.<br>
       <div id="geocoding"> </div>
      </div>
</div>