<h1><?php echo $this->translate(\JumpUpDriver\Util\Messages\IViewMessages::VEHICLE_ADD); ?></h1>

<div class="hint">
  <?php 
    // show infoMessages if possible
    if(null !== $this->infoMessages && is_array($this->infoMessages)) {
      foreach ($this->infoMessages as $infoMessage) {
        echo "<p>".$this->translate($infoMessage)."</p>";
      }
     
    }
  
  
  ?>
</div>

<div id="add-vehicle" class="form registration">
<?php 
    /*
     * author: Sascha Feldmann
     * 
     * what a nice view. we just delegate the form to our view helper object.
     * See Application\View\Helper\RenderForm.php
     */
    if(null !== $this->form) { // form is exported by the controller
        $form = $this->form;   
         echo $this->renderForm($form); 
    }
    else { // a message shall be shown
        echo $this->translate($this->message);
    }
  
   
?>

</div>

