<h1><?php echo $this->translate(\JumpUpDriver\Util\Messages\IViewMessages::VEHICLE_LIST) ?></h1>

<div class="form registration">
<?php
/*
 * author: Sascha Feldmann what a nice view. we just delegate the form to our view helper object. See Application\View\Helper\RenderForm.php
 */
use Application\Util\FilesUtil;
use JumpUpDriver\Util\Messages\IViewMessages;
if (null !== $this->messages) {
	foreach ( $this->messages as $message ) {
		echo $this->translate ( $message ) . "<br />";
	}
}

$addUrl = $this->addUrl;
echo "<a href=\"${addUrl}\">" . $this->translate ( IViewMessages::VEHICLE_LIST_LINK_ADD ) . "</a><br /><br />";
if (null !== $this->vehicles) { // form is exported by the controller
	if (0 == sizeof ( $this->vehicles )) {
		echo $this->translate ( IViewMessages::VEHICLE_LIST_NO_VEHICLES );
	}
	foreach ( $this->vehicles as $vehicle ) {
		$removeUrl = $this->removeUrl . "?" . $this->identifierParam . "=" . $vehicle->getId ();
		$editUrl = $this->editUrl . "?" . $this->identifierParam . "=" . $vehicle->getId ();
		
		echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_BRAND ) . ":</span>" . $vehicle->getBrand () . "<br />";
		echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_TYPE ) . ":</span>" . $vehicle->getType () . "<br />";
		echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_WASTAGE ) . ":</span>" . $vehicle->getWastage () . "<br />";
		echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_AVG_SPEED ) . ":</span>" . $vehicle->getAvgspeed () . "<br />";
		echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_SEATS ) . ":</span>" . $vehicle->getNumberseats () . "<br />";
		echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_LEG_SPACE ) . ":</span>" . $vehicle->getLegspace () . "<br />";
		echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_AIR_CONDITION ) . ":</span>" . $this->translate ( $vehicle->getAircondition () ) . "<br />";
		echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_ACTUAL_WHEEL ) . ":</span>" . $this->translate ( $vehicle->getActualwheel () ) . "<br />";
		echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_ENGINE_TYPE) . ":</span>" . $this->translate ( $vehicle->getEnginetype() ) . "<br />";
		if (null !== $vehicle->getVehiclepic ()) {
			echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_CURRENT_PIC ) . ":</span>" . FilesUtil::prepareVehiclePic ( $vehicle ) . "<br />";
		} else {
			echo $this->translate ( IViewMessages::VEHICLE_LIST_NO_PIC );
		}
		echo "<a href=\"${removeUrl}\">" . $this->translate ( IViewMessages::VEHICLE_LIST_LINK_REMOVE ) . "</a> ";
		echo "<a href=\"${editUrl}\">" . $this->translate ( IViewMessages::VEHICLE_LIST_LINK_EDIT ) . "</a>";
		echo "<br /><br />";
	}
}

?>

</div>

