<?php
use JumpUpDriver\Util\Messages\IViewMessages;
use Application\Util\FilesUtil;
?>
<h1><?php echo $this->translate(\JumpUpDriver\Util\Messages\IViewMessages::SHOW_VEHICLES) ?></h1>


<div id="vehicles_hints">
<?php
if (null !== $this->messages) {
	foreach ( $this->messages as $message ) {
		echo "<p>" . $message . "</p>";
	}
}
?>
</div>

<div class="vehicleview">
<?php
if (null !== $this->vehicle) {
	echo $this->translate ( IViewMessages::VEHICLE_LIST_BRAND ) . ": " . $vehicle->getBrand () . "<br />";
	echo $this->translate ( IViewMessages::VEHICLE_LIST_TYPE ) . ": " . $vehicle->getType () . "<br />";
	echo $this->translate ( IViewMessages::VEHICLE_LIST_WASTAGE ) . ": " . $vehicle->getWastage () . "<br />";
	echo $this->translate ( IViewMessages::VEHICLE_LIST_AVG_SPEED ) . ": " . $vehicle->getAvgspeed () . "<br />";
	echo $this->translate ( IViewMessages::VEHICLE_LIST_SEATS ) . ": " . $vehicle->getNumberseats () . "<br />";
	echo $this->translate ( IViewMessages::VEHICLE_LIST_LEG_SPACE ) . ": " . $vehicle->getLegspace () . "<br />";
	echo $this->translate ( IViewMessages::VEHICLE_LIST_AIR_CONDITION ) . ": " . $vehicle->getAircondition () . "<br />";
	echo $this->translate ( IViewMessages::VEHICLE_LIST_ACTUAL_WHEEL ) . ": " . $vehicle->getActualwheel () . "<br />";
	if (null !== $vehicle->getVehiclepic ()) {
		echo $this->translate ( IViewMessages::VEHICLE_LIST_CURRENT_PIC ) . ": " . FilesUtil::prepareVehiclePic ( $vehicle ) . "<br />";
	} else {
		echo $this->translate ( IViewMessages::VEHICLE_LIST_NO_PIC_FOR_PASSENGER );
	}
}

?>

</div>

