<?php
use JumpUpDriver\Util\Messages\IViewMessages;
use Application\Util\FilesUtil;
?>
<h1><?php echo $this->translate(\JumpUpDriver\Util\Messages\IViewMessages::SHOW_VEHICLES) ?></h1>


<div id="vehicles_hints">
<?php
if (null !== $this->messages) {
	foreach ( $this->messages as $message ) {
		echo "<p>" . $message . "</p>";
	}
}
?>
</div>

<div class="vehicleview">
<?php
if (null !== $this->vehicle) {
	echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_BRAND ) . ":</span>" . $vehicle->getBrand () . "<br />";
	echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_TYPE ) . ":</span>" . $vehicle->getType () . "<br />";
	echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_WASTAGE ) . ":</span>" . $vehicle->getWastage () . "<br />";
	echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_AVG_SPEED ) . ":</span>" . $vehicle->getAvgspeed () . "<br />";
	echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_SEATS ) . ":</span>" . $vehicle->getNumberseats () . "<br />";
	echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_LEG_SPACE ) . ":</span>" . $vehicle->getLegspace () . "<br />";
	echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_AIR_CONDITION ) . ":</span>" . $this->translate ( $vehicle->getAircondition () ) . "<br />";
	echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_ACTUAL_WHEEL ) . ":</span>" . $this->translate ( $vehicle->getActualwheel () ) . "<br />";
	echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_ENGINE_TYPE ) . ":</span>" . $this->translate ( $vehicle->getEnginetype () ) . "<br />";
	if (null !== $vehicle->getVehiclepic ()) {
		echo "<span class=\"key-value--key\">" . $this->translate ( IViewMessages::VEHICLE_LIST_CURRENT_PIC ) . ":</span>" . FilesUtil::prepareVehiclePic ( $vehicle ) . "<br />";
	} else {
		echo $this->translate ( IViewMessages::VEHICLE_LIST_NO_PIC_FOR_PASSENGER );
	}
}

?>

</div>

