<h2><?php echo $this->translate(\JumpUpPassenger\Util\Messages\IViewMessages::BOOKING_ERROR); ?></h2>

<div class="content"> 
<?php 
    if ($this->messages) {
        echo '<ul>';
        foreach($this->messages as $message)
        {
            echo '<li>'.$this->translate($message).'</li>';
        }
        echo '</ul>';
    }
    
    if($this->errorMessages) {
      echo '<ul>';
      foreach($this->errorMessages as $message)
      {
        echo '<li>'.$this->translate($message).'</li>';
      }
      echo '</ul>';
    }
?>
</div>