<?php
use JumpUpPassenger\Util\Messages\IControllerMessages;
use Application\View\Helper\RenderBookings;
?>


<h2><?php echo $this->translate(\JumpUpPassenger\Util\Messages\IViewMessages::VIEW_BOOKINGS_TITLE); ?></h2>

<div id="passenger_hints">
<?php
if (null !== $this->messages) {
	foreach ( $this->messages as $message ) {
		echo "<p>" . $this->translate ( message ) . "</p>";
	}
}

?>
</div>

<div class="content" id="view-passenger-bookings">
	<div id="passenger_view_bookings">
<?php

if (null !== $this->bookings && (0 < sizeof ( $this->bookings ))) {
	echo '<div id="accordion">'; // start of accordion
	foreach ( $this->bookings as $booking ) {
		RenderBookings::renderBookingForPassenger ( $booking, $this );
	}
	echo "</div>"; // end of accordion
} else { // no bookings done
	echo $this->translate ( IControllerMessages::BOOKING_NO_BOOKINGS );
}

?>
</div>
</div>

